// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUQAUQ9NjBDAKUERkJUMMwTdnDvO53ZvI',
    appId: '1:688512555078:web:1f12f0f249520c9920d247',
    messagingSenderId: '688512555078',
    projectId: 'chat-app-47afe',
    authDomain: 'chat-app-47afe.firebaseapp.com',
    storageBucket: 'chat-app-47afe.appspot.com',
    measurementId: 'G-8K1CB4DDPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGtgha-rVhULspvubnLFAAvPLvEj7Ax0',
    appId: '1:688512555078:android:1ce924297819e03620d247',
    messagingSenderId: '688512555078',
    projectId: 'chat-app-47afe',
    storageBucket: 'chat-app-47afe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrad7zPUrkWUIJOfgnqgpSVbhwR77ybMk',
    appId: '1:688512555078:ios:5c4d419db890287520d247',
    messagingSenderId: '688512555078',
    projectId: 'chat-app-47afe',
    storageBucket: 'chat-app-47afe.appspot.com',
    iosClientId: '688512555078-kkebjhk63biaa2qaf2n6jobthisr7eib.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrad7zPUrkWUIJOfgnqgpSVbhwR77ybMk',
    appId: '1:688512555078:ios:c7f0076a25524a9f20d247',
    messagingSenderId: '688512555078',
    projectId: 'chat-app-47afe',
    storageBucket: 'chat-app-47afe.appspot.com',
    iosClientId: '688512555078-11i54vd8mmrpuobs3brv5j288j82tkq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
